### PR TITLE
Split Sign in / Sign out into two different view controllers

### PR DESCRIPTION
**Pull request by patricks**
This should fix the issue #679

### CODE REVIEW

**Comment by bryceco** [comment]
This looks great, thank you so much! 
If I try logging out and then logging back in the user name field is blank, and I tracked it down to the usernameLabel's frame size being 0,0. Unfortunately Xcode didn't want to open the xib (old version maybe) so I couldn't check the constraints you were using, so could you take a look?

**Comment by patricks** [comment]
Thanks for your feedback I'll look into it. Let me check if I also can fix the Xcode Storyboard problem.

**Comment by bryceco** [comment]
The storyboard problem was with an Xcode setting, so that's on me!

**Comment by bryceco** [comment]
This looks good!

 There is still one thing that is a little confusing for users: If you revoke access from the website and then go back to the app you get a "Bad Login" error message, and then have to press the "Sign Out" button and then "Sign In" which is a little counterintuitive. Not sure what to do about that.

**Pull request merged**
