### PR TITLE
Refactoring: Move `UploadViewController` to a dedicated storyboard

### PR DESCRIPTION
**Pull request by wtimme**
By moving the view controller to a dedicated storyboard, we make it easier to modify the view controller (e. g. for #239). In addition, the size of the `MainStoryboard` is reduced, resulting in lower risk of merge conflicts.

### CODE REVIEW

**Comment by wtimme** [comment]
I've created a [temporary branch][1] for _OSM-Completionist_ and made a TestFlight version available (_OSM Completionist 1.7.0 (32)_) so that everyone (pinging @tordans) is able to do the QA.

## What needs to be tested?

Basically, the upload flow - both signed-out and signed-in.

Thanks in advance for your feedback!

[1]: https://github.com/wtimme/OSM-Completionist/compare/feature/239-Move-UploadViewController-to-dedicated-storyboard-from-develop

**Comment by bryceco** [comment]
When compiling there's a warning: "Push segues are deprecated since iOS 8.0"

I understand the desire to split the storyboard up, but is moving a single view to its own storyboard the correct approach? I'd think it would be more effective to split off the Display and Settings into their own storyboards since they're both fairly large and contain many views of their own.

**Comment by wtimme** [comment]
Thanks for taking a look and checking out the branch, Bryce!

> When compiling there's a warning: "Push segues are deprecated since iOS 8.0"

That is correct. When moving the scene to the new storyboard, I made sure to apply the same settings for the _Storyboard Segue_ again. I just checked one more time, and yes, on `master`, the segue is using the same settings. I don't know why my branch is showing the warning; maybe that's because the storyboard is "newer"?

> is moving a single view to its own storyboard the correct approach?

I chose "Changeset" for the name of the storyboard. In the future, the storyboard could also house (just an example, bear with me) a view controller that displays all of the mapper's changesets.

> I'd think it would be more effective to split off the Display and Settings into their own storyboards since they're both fairly large and contain many views of their own.

My goal was to prepare the project for changes in regards to #239. Sure, we can just keep everything in the "MainStoryboard", but that comes with a couple of downsides:
- Potential merge conflicts due to unwanted changes that were automatically introduced by Xcode
- Slower development time, since the "MainStoryboard" takes a lot of time to load (at least on my machine)

In addition, we also have to consider the fact that this is an Open Source project, and people only have _so much_ time. Personally, I am trying to do baby steps in the right direction, and to gradually introduce changes. As an example, look at this PR: It's fairly small, allowing for a quick review and discussion of the changes.

Merging the changes proposed in this PR will allow other developers to further integrate changes needed for #239, and they can already benefit from the effort and time that I put in.

**Comment by wtimme** [comment]
> When compiling there's a warning: "Push segues are deprecated since iOS 8.0"

I've taken another look and changed the segue from "Push" to "Show", and tested it without being logged in. The login is pushed just like before, and the warning is gone.

**Comment by wtimme** [comment]
With the recent changes (splitting the main storyboard into several smaller ones), we introduced conflicts that need to be resolved. I am sure they can be resolved with a bit of effort, so that this pull request _could_ be merged again.

However (and I hope I don't sound too dramatic), I am a bit disappointed and, to be honest, frustrated in the way that this contribution was handled. Let me tell you why.

---

While skimming through the open issues, I found a rather small one in which users requested a small UI change (#239) that would not only help them, but make GoMap look more professional when looking at the changesets it introduces.

I realized that at its current state (back then), changes to the `Main.storyboard` might result in merge conflicts in case someone else was also doing changes, so I decided to first move the `UploadViewController` (the one in which we would introduce a new UI element for the `source` tag) to a dedicated storyboard.

This was meant as an operation with very low negative impact on everyone:
- I wanted other contributors to experience little to no merge conflicts
- The changes (and thus, the PR) should be fairly small, so that it is easy to review ([take a look again][1] - it's only 5 files that were changed)
- The functionality change should be small as well, so that it is easy to QA

In short, the pull request and its changes aimed at being easy on everyone's shoulders.

After a few days, I got feedback from you (thanks again!) and resolved it. 

---

In the last couple of days, you took on the challenge of splitting up the storyboard into several smaller ones, and this comes with quite a few benefits for everyone, so thanks again for your effort! However, doing changes to the storyboard (and, in the end, removing it) meant that _this_ pull request here gets merge conflicts.

In the end, I guess what I am trying to say is that I would have liked for either to get more feedback (especially as to _what exactly_ is blocking this pull request from being merged), or for this pull request to be merged _before_ doing all these changes to the storyboard.

I realize that this is not a big issue, and I could also just resolve the conflicts and carry on. But I wanted to take this opportunity to detail why things like this pull request are draining my motivation.

I am sure that you have a lot of stuff on your plate, and maintaining an app as complex as GoMap is a time-consuming task. Please don't take this comment the wrong way - I am not trying to blame, and I don't want to _complain_. I just wanted to write down my perspective, and I understand that I don't have the full picture.

Thanks for reading. I am always open for feedback, be it in the comments, via email or on Slack.

[1]: https://github.com/bryceco/GoMap/pull/313/files

**Comment by bryceco** [comment]
I understand your frustration and I apologize. There are a couple reasons I didn’t merge this pull request immediately: I understand we have different development backgrounds and styles. While I’ve been a professional developer my entire life, I’ve only been an Apple/iOS developer for this project, and only as a hobby. You are more familiar with more modern techniques and workflows than I. My building blocks in projects tend to be fairly large, reflecting the fact that I’ve always developed in very small teams where merge conflicts were essentially non-existent. 

While I agree the storyboard was too large and cumbersome, I think going back to the XIB pattern of one per controller is too far the other direction. Since there is only a handful of people submitting code I’m willing to risk some degree of merge conflicts in order to let the storyboard express the UI flow more fully. If you feel the merge burden is too great we can discuss that. 

If you had submitted this with the expectation of adding the other functionality yourself then that would have been fine, but instead this was work done to benefit a hypothetical future developer. If the person who ends up implementing #239 is me (which is fairly likely) then this change doesn’t do anything to make that easier. I’m the primary maintainer of this code base, so changes which introduce churn without adding features/fixes are a bit of a negative to me. Having the entire project in a single storyboard except for one scene seemed arbitrary and unintuitive. 

With all that said, I confess that after I finished splitting the storyboard I rather regretted not merging the split of Upload as well (for symmetry reasons primarily). As punishment I’ll resolve the introduced conflicts on this and merge it myself. 

Thanks for all your contributions!

**Pull request merged**
