### PR TITLE
Allow to measure "direction" and "camera:direction" using device compass

### PR DESCRIPTION
**Pull request by wtimme**
> As a mapper, I want to make use of my device' compass when setting the "direction" or "camera:direction" tag, so that I can add this detail more easily

This branch adds a new view controller that allows users to measure the value for the tags "direction" and "camera:direction" using the compass.

The new view controller can be reached by tapping at the (new) disclosure indicator:

1-disclosure-indicator

The app uses the device' compass to measure the direction. The user can choose to update the tag or cancel the measurement:

2-measure-direction

### CODE REVIEW

**Comment by bryceco** [comment]
This looks pretty cool, and I've read over the code. I'm a git newb so I'm not sure how to pull your branch so I can run and test it before committing. What is the git syntax?

What do you think of having the direction view come up from the bottom and obscure the Tab Bar, so it matches how the Turn Restriction and Measure Height modals work? Also I'm not crazy about having both a Cancel button and a Back button which I'm guessing are synonymous?

**Comment by wtimme** [comment]
Thanks for the feedback! To pull the branch, you need to add my repository as a new "remote":

    % git remote add wtimme https://github.com/wtimme/GoMap.git

You should then be able to checkout my branch like so:

    % git checkout wtimme:feature/Measure-the-direction

If you need more help or if the above commands don't work as expected, just let me know.

I'll have a look at your feedback in detail later today and get back to you. Thanks again for you input!

**Comment by wtimme** [comment]
Did you manage to get it to work?

> What do you think of having the direction view come up from the bottom and obscure the Tab Bar, so it matches how the Turn Restriction and Measure Height modals work?

Sounds like a good idea.

> Also I'm not crazy about having both a Cancel button and a Back button which I'm guessing are synonymous?

If the view controller was to present modally, there wouldn't be a Back button, so we could leave the Cancel button.

What do you propose - should I go ahead and present the view controller modally?

**Comment by bryceco** [comment]
Yes please change it to modal. (I’m in Seattle so our time zones are offset a bit.)

**Comment by bryceco** [comment]
$ pwd
/Users/bryce/SourceCode/GitHub/GoMap
$ git remote add wtimme https://github.com/wtimme/GoMap.git
$ git checkout wtimme:feature/Measure-the-direction
error: pathspec 'wtimme:feature/Measure-the-direction' did not match any file(s) known to git
$

**Comment by wtimme** [comment]
Sorry, I should've tried this before posting. I was in a rush. 😅 Here's what you need to do:

    % git remote add wtimme https://github.com/wtimme/GoMap.git
    % git fetch wtimme
    % git checkout feature/Measure-the-direction

Without fetching, Git doesn't know about my branches.

**Comment by wtimme** [comment]
So this took me a little bit. Presenting the view controller modally was pretty straight-forward, but for some reason, the direction was always reset back to the original value.

Turns out, the `POITabBarController` rebuilds the `keyValueDict` with every `viewWillAppear:`.
I've changed it in a way that it only builds the `keyValueDict` when it is `nil`.

Did you succeed in checking out the branch?

**Comment by bryceco** [comment]
I got it checked out, but something is broken. When I create a new node and select a Type for it the value isn't updated.

**Comment by tordans** [comment]
@wtimme this sounds like a great addition <3.

Will this feature also work for **`roof:direction`** (https://wiki.openstreetmap.org/wiki/Key:roof:direction)?

Will the input be able to transpose the `NW`-etc-values that https://wiki.openstreetmap.org/wiki/Key:direction talks about to a degree-value? Or how will those edge cases where direction != Number be handled by the UI?

**Comment by tordans** [comment]
About the Git/GitHub questions, another way to check out a pull requests is explained at https://help.github.com/en/articles/checking-out-pull-requests-locally

**Comment by wtimme** [comment]
> When I create a new node and select a Type for it the value isn't updated.

Yes, I can reproduce that, thanks for spotting this! I'll have a look.

**Comment by wtimme** [comment]
So I tried to fix the modal presentation, but to no avail. I still haven't figured out completely how the whole view controller works, and I'm afraid I'll mess something up (like just now).

That's why I have gone back a step. The view controller is now no longer presented modally, but instead "pushed".

Furthermore, the "Cancel" button is now hidden when the view controller is not presented modally, so it looks like this:

pushed-view-controller

Can this work as an MVP? It is already usable in the current iteration, and I think it adds value to the app. What do you think?

**Pull request merged**
