### PR TITLE
Create protocol for database in `OsmMapData`

### PR DESCRIPTION
**Pull request by wtimme**
This branch adds a protocol `Database` and renames the existing, concrete implementation of the database to `SQLite3Databaes`. Using a protocol allows for the mocking of the `Database` in unit tests.

The initial reason for adding this protocol was that, while writing unit tests, the assertions in `initWithCachedData` were triggered, because the database returned `nil`. I've changed the three query methods so that they no longer return `nil`, removing the need for the assertions.

### CODE REVIEW

**Comment by wtimme** [comment]
Does someone have feedback on these changes? Thanks in advance!

**Comment by bryceco** [comment]
I did a review two weeks ago when you submitted it. Do you not see my comments?

**Comment by wtimme** [comment]
Thanks for getting back to me!

I might have missed them. 😅 Where can I find them?

**Comment by bryceco** [comment]
They’re right above us, when I’m reading this page: https://github.com/bryceco/GoMap/pull/226#issuecomment-491404655

**Comment by wtimme** [comment]
Hmm, for some reason I am not able to see any comments. Here's what this page looks like on my end:

Screenshot of the discussion for this pull request

**Comment by tordans** [comment]
Might it be that you are in a review process that needs finishing via the button on the top right before the comments are visible?

It’s a new GitHub feature „add single line comment“=visible immediately. Or „add review comment“=only visible after review finished.

**Comment by bryceco** [comment]
You were correct, the “Submit Review” wasn’t visible on mobile.

**Pull request closed without merging**
