### PR TITLE
Add "Download on the App Store" badge to README

### PR DESCRIPTION
**Pull request by wtimme**
This branch adds a badge to the README that links to GoMap on the App Store, making it easier for users to install it.

Using my branch, you can [preview the rendered README][1].

[1]: https://github.com/wtimme/GoMap/tree/feature/Update-README#readme

### CODE REVIEW

**Comment by bryceco** [comment]
Can this be put on the wiki page as well?

**Comment by wtimme** [comment]
Yes, that is possible. Which wiki page are you referring to?

**Comment by bryceco** [comment]
https://wiki.openstreetmap.org/wiki/Go_Map!!

**Comment by wtimme** [comment]
I believe we could upload the image to the Wiki, yes. What's the benefit for the user over the information box that also contains the link to the App Store?

**Comment by bryceco** [comment]
I guess there’s no added benefit except it’s prettier.

**Pull request merged**
