### PR TITLE
fix(zh-Hant.xliff): changed two strings

### PR DESCRIPTION
**Pull request by olivertzeng**

### CODE REVIEW

**Comment by olivertzeng** [comment]
https://github.com/olivertzeng/GoMap/blob/eb30fd4b0a4f1177a1fc7ec7626e422807fcda8c/src/xliff/zh-Hant.xliff?plain=1#L3418
you might wanna change the copyright year

**Comment by bryceco** [comment]
Thanks for this, but please modify translations on the [translation website](https://hosted.weblate.org/projects/go-map/app/) where changes are centralized. The xliff files are just an intermediate format for moving translations back and forth to weblate. Now that we're using .xcstrings files we could probably stop checking them in to GitHub altogether.

> you might wanna change the copyright year

I could, but then all the translators would have to update that wall of text and I don't want to annoy them :)

**Comment by olivertzeng** [comment]
> Thanks for this, but please modify translations on the [translation website](https://hosted.weblate.org/projects/go-map/app/) where changes are centralized. The xliff files are just an intermediate format for moving translations back and forth to weblate. Now that we're using .xcstrings files we could probably stop checking them in to GitHub altogether.
> 
> > you might wanna change the copyright year
> 
> I could, but then all the translators would have to update that wall of text and I don't want to annoy them :)

whoa that was fast thanks! ill be sure do that there!
also you should probably link the weblate on README.md as well
I've seen [this](https://timonwa.com/blog/autoyear-copyright-update) and in that way you would only need to change it once idk if that works!

**Comment by bryceco** [comment]
Yeah, we could add some code to the app to convert "2012-2020" to the correct year. 

The README mentions Weblate in the External Assets section. It's also referenced inside the app under Contact Us.

**Comment by bryceco** [comment]
b2774554d3504892d7235f56af5e2f1b939e31bf

**Pull request closed without merging**
