### PR TITLE
Refactoring: Remove code that is enclosed by `#if 0`

### PR DESCRIPTION
**Pull request by wtimme**
This branch removes a lot of code that was commented out or enclosed by `#if 0` conditions.

I do realize that these are quite some changes, and that it (at least in parts) removes some of the effort that was already put it, e. g. for future features. That is why I tried to split the pull request into as much (meaningful) commits as possible. This allows us to later retrieve all the changes back from the Git history, meaning that nothing is lost.

My main goal here was to reduce the amount of (unused) code that one needs to read in order to understand the repository and all of its files, enabling an easier access to fellow developers.

I hope that the changes are not too drastic, and that you are not taken aback from all the deletions. If the features that were commented-out (e. g. `VoiceAnnouncement`) are to be used again in the future, we can simply revert that particular commit, or copy the code from the diff.

**Please let me know how you feel about this.** I have the utmost respect for the effort (and time!) you've already put into this project, and I hope you know that a lot of people appreciate the work you are doing. By making the codebase even easier to understand, I hope we can get more people to join the cause. Thanks in advance for your time!

### CODE REVIEW

**Comment by bryceco** [comment]
It would be great if we could move the code for future features into separate branches rather than simply deleting it. Unfortunately my git skills are pretty poor and I don’t know how to do that.

The branches would be for:
* VoiceAnnouncement (announces streets and POIs while walking/driving so you can verify correctness)
* HTMLAlertView (to display certain network errors that are returned as an HTML string,  such as captive portal messages)
* SpeechBalloonView (for a walkthrough tutorial mode)
* TapAndDragGesture (alternate zooming UI which is used by google maps)

I’m not terribly concerned if you delete logging/debugging code.

**Comment by wtimme** [comment]
Thanks for sharing your thoughts, and for being so open for discussion!

I fully agree. That code is best kept in dedicated branches. The whole day today I was contemplating how to properly explain it, but [this article from Kent Dodds][1] sums it up pretty well.

### How to create branches for the features

The steps to "recover" that code and create a new branch from it is pretty straight forward.
Make sure you're on our development branch (currently `master`):

    % git checkout master

Create a new branch:

    % git checkout -b feature/VoiceAnnouncement

Now, locate the hashes of the commits that you want to revert ("undo"). You can use GitHub to [get a list of commits for this pull request][2], and copy them by clicking.

In reverse chronological order, use `git revert` for each commit:

    % git revert --no-edit 5681cac73009086570a00ac833371fc7a56deb08

You might encounter merge conflicts, but as long as your commits are partial (meaning: as small as possible), they are more or less easily solved. You can see the result [in my repository][3].

[1]: https://kentcdodds.com/blog/please-dont-commit-commented-out-code
[2]: https://github.com/bryceco/GoMap/pull/174/commits
[3]: https://github.com/wtimme/GoMap/compare/refactoring/Remove-unused-code...wtimme:feature/VouceAnnouncement?expand=1#files_bucket

**Comment by wtimme** [comment]
Have you found the time to look into my comment and the branch that I prepared? Is there something that I can do here to make you more comfortable with removal of the old code?

**Comment by bryceco** [comment]
I just noticed last night that your repository has that code in dedicated branches. I’ll take a closer look at it today.

**Comment by bryceco** [comment]
How do I pull the feature branches you created into master?

**Comment by wtimme** [comment]
What are you trying to achieve? If you wanted to do a checkout of that branch to work on it, that's pretty straight forward.

Make sure that you're on `master`:

    % git checkout master

Make sure that you've added my repository as a remote:

    % git remote add wtimme https://github.com/wtimme/GoMap.git

Run `fetch` so that you can see all my branches:

    % git fetch wtimme

Finally, just checkout the branch, just like you'd normally do:

    % git checkout feature/VouceAnnouncement

And you're good to go.

If you actually wanted to merge that feature branch into `master` right away, make sure you're on `master` and run

    % git merge feature/VouceAnnouncement

---

I hope that helps.

**Comment by bryceco** [comment]
I want a copy of the feature/VoiceAnnouncement branch to live under bryceco rather than wtimme.

**Comment by wtimme** [comment]
So to put it simple, you want to basically "copy" it? That's easily done. Make sure you follow the steps above and checkout my branch.

Now you already have a copy of it _locally_, on your computer. Assuming you have setup GitHub as your `origin`, you can now push the code to GitHub by running

    % git push origin feature/VouceAnnouncement

Now, your copy of the branch can live on _your_ GitHub repository. 👍🏼

**Comment by wtimme** [comment]
Hey @bryceco, did you find the time to look into this? Is there more information that I can provide? Sorry for bumping! I just want to make sure the branch doesn't go stale.

**Pull request closed without merging**
