### PR TITLE
Fix: "unsupported url" error message during upload

### LINKED ISSUE #212: Bug: Error message "unsupported url"
I wrote a longer commit message today and received a weird error message 

> Unable to upload changes
> Unsupported URL
> <OK>

Once I shortened the message by removing everything including the "// …", the commit went through. 

I am pretty sure this error message is not right here. Cause I did not change anything URL related, but the commit went through.
- Maybe the "message too long" error has the wrong message?
- Maybe the "//" in the commit message causes a weird error?

### PR DESCRIPTION
**Pull request by wtimme**
This branch fixes #212.

There are a couple of changes:
1. Spell checking is now disabled for the "username" field
2. Only _verified_ (= correct) credentials are stored in the `KeyChain`
3. When changing the server and providing an URL without `/` as the suffix, the app only adds a single `/` to it - not two
4. Improve error handling for when the server does not respond with a numeric ID while attempting to create a changeset

### CODE REVIEW

**Comment by bryceco** [comment]
I’m a little confused by this. What is the behavior if the user enters their credentials and then presses back without verifying? It just deletes the information they entered? That seems worse than before.

**Comment by wtimme** [comment]
> What is the behavior if the user enters their credentials and then presses back without verifying?

The credentials are _not_ saved. Only successfully verified credentials are stored in the `KeyChain`.

**Comment by tordans** [comment]
So before: The verify-link was an optional step. It was enough to open the panel, provide input and tab "back". The data was saved but not verified at this point.

And now: The verify-link is a required step to finish the account input. Only once verified, the data is saved. The "back" will discard data, that was to verified yet.

I am really unsure about those UI pattern. Both feel non-ideal. The old does not really match what I expect. And the new does not say loudly enough "you have to click verify first".

A quick fix could be for the new UI:
In case the user changes data and clicks "back" without verifying first, there could be an alert:
> You changed your data login data.
> Please verify or undo to discard your changes.
> [Verify & save] [Undo & back]

This way we have the users covered at least.

Generally I don't like alert-based UI flows, but I think here its the quickest solution and not too bad since I only provide my data once.

**Comment by bryceco** [comment]
If credentials are only saved when you press verify then that button should be labeled Save.

**Comment by wtimme** [comment]
> Generally I don't like alert-based UI flows

> If credentials are only saved when you press verify then that button should be labeled Save.

Absolutely agreed. 👍🏼 I've updated the button's title and renamed the property (to `saveButton`) so that it matches the new title.

**Pull request merged**
