### PR TITLE
Update LocationParser.swift

### PR DESCRIPTION
**Pull request by timskap**
Change Link host for Google Maps Decoder

### CODE REVIEW

**Review by bryceco — CHANGES_REQUESTED** [review]
I'm sure this worked as I wrote it in at least one situation, so could we check both your and my host names?

**Comment by timskap** [comment]
I'm not sure that this will work properly. I decided to additionally test code and find out that redirect link comes without lat long and parser couldn't get a position. 

This is an example of redirected link: https://maps.google.com/maps?q=Nile,+5a,+Tbilisi&ftid=0x40446d87c19dcec9:0x5822f57eaece365a&hl=en-GE&gl=ge&entry=gps&lucs=,47071704&g_ep=CAISDDYuOTMuMy4yNTkyMBgAINeCAyoJLDQ3MDcxNzA0QgJHRQ%3D%3D

**Comment by timskap** [comment]
Probably I miss something but thank you for fast response

**Comment by bryceco** [comment]
Thanks! I'll take a look and report back 🫡

**Comment by timskap** [comment]
So I tested almost everything that I could. They changed the logic of short links and now it redirects to new version that "changes link" a little bit after a loading of page. And before that it shows a link with "ftid". Ftid is a hex value that could transform to cid and then could be only transform to lat long by Google APIs. They did that intentionally to force people to use their API.

**Comment by timskap** [comment]
The only works solution is using Places API, but I also found that if you choose a random place in nowhere it returns a coordinates as expected. 😾

**Comment by timskap** [comment]
I updated a script but this will work only with API.

**Comment by bryceco** [comment]
Wow, this looks great!

**Comment by timskap** [comment]
Remove parenthesis from request. My bad.

**Comment by bryceco** [comment]
Sorry about the long pause. I finally got my Google API key set up and this is now integrated! Thanks a bunch!

**Pull request merged**
