### PR TITLE
Fix: Blurry street names

### PR DESCRIPTION
**Pull request by wtimme**
With this branch, the street names are no longer blurry.

## Comparison*

`shouldRasterize = YES`
01-blurry

`shouldRasterize = NO`
02-not-blurry

\* The difference might not be as noticable due to image compression, but it makes quite a different on an actual device. 👍🏼

### CODE REVIEW

**Comment by bryceco** [comment]
Rasterizing was enabled in the hope that it would increase rendering performance. Drawing text is about 20% of the render cycle and frame rate is a concern on older devices. I don’t remember what the actual impact was. 

If you search the source for FpsLabel there is an Easter Egg where you create a node with some special tags and the app will display the frame rate, allowing you to do some rudimentary comparisons.

**Comment by tordans** [comment]
> If you search the source for FpsLabel there is an Easter Egg where you create a node with some special tags and the app will display the frame rate, allowing you to do some rudimentary comparisons.

Challenge accepted ;-). 

Is it OK to post them here or will I spoil the search for anyone :).

**Comment by bryceco** [comment]
Yes you can document them here

**Comment by wtimme** [comment]
Interesting background info, thanks for sharing, @bryceco! Do you have a coordinate on the map that is very busy when it comes to street names, so that we can compare the performance?

Furthermore, I would love for the "Show FPS" to be an official debug setting that anybody can use, not just code treasure hunters. ;) What do you think?

**Comment by bryceco** [comment]
I don’t have a favorite location for testing drawing performance. I typically just use the neighborhood nearby. I think there is a hard cap on the number of street names it tries to render, around 20, so just zoom out a bit. 

Depending on the results you find it’s also possible to change the setting based on the cpu. I already trim the number of objects rendered on older hardware.

**Comment by bryceco** [comment]
When you say a “debug setting” do you mean a build setting?

**Comment by wtimme** [comment]
I've created a dedicated feature request for the build setting (#218).

As for this pull request, I'd like to help out with testing. Is there any strategy that one could follow, @bryceco? Some places on the map where you or other users experienced degraded performance?

Could we maybe mock the server's response and return pre-calculated mock data, e. g. 200 random streets?

**Comment by tordans** [comment]
> Could we maybe mock the server's response and return pre-calculated mock data, e. g. 200 random streets? We could then scroll around in that mock data and try to see if there are any performance issues.

The way I understood the issue is: We need to go somewhere with a lot of roads and compare the FPS with both settings to validate, if the performance (still) is an issue.

So IMO that could be any place with many roads, like Manhatten for example https://www.openstreetmap.org/#map=13/40.7443/-74.0009

What are the FPS-values for this place (different zoom levels, panning around) for both cases (feature on/off)? (On the phone, not the emulator ;))

**Comment by bryceco** [comment]
It’s better to go to a place with lots of roads but no other POIs. Basically any residential neighborhood that lacks buildings. These are super common in OSM. There should be either another Easter egg or some #if 0 code that will pan the map in a square pattern continuously to help with having uniform motion without downloading new data. Obviously the goal is 60 FPS.

**Comment by wtimme** [comment]
Are you referring to the `FRAMERATE_TEST`?

```
#define FRAMERATE_TEST	1
```

automatically pans around the map.

On my iPhone X, I get more or less steady 60 FPS at the start position of the scrolling demo.

However, when I pan around quicker and more random, the FPS sometimes drop as low as 2.80. **This happens regardless of whether `shouldRasterize` is set to `YES` or to `NO`.**

fps-of-2_90
(`shouldRasterize` was set to `YES`.)

Could you verify this, @tordans? I zoomed out a little bit and randomly panned around on the map, trying to get the FPS low. Can you reproduce this?

**Comment by bryceco** [comment]
You really need to test on older harder than iPhone X. I use my old 32-bit iPad 3 for tests like this. 

When scrolling randomly it’s pretty easy to accidentally download new data which slows things down.

**Comment by tordans** [comment]
> Could you verify this, @tordans? I zoomed out a little bit and randomly panned around on the map, trying to get the FPS low. Can you reproduce this?

I can only test the test flight version, which does not have thin change, right?

**Comment by tordans** [comment]
**Ideas about how to get this merged:**

- We dont have a proper testing setup, so we cannot really know what is "good"/"working"/"ok performance".
- We dont want to release something that makes the performance bad of old devices

How about …
- We make this an advanced option for now, so we can test it in real live for a while. We can then test it on several devices (of friends) without the whole testing-authentication-process.
or
- We make it active for the newest hardware, but inactive for the older once. We can then remove it in about two years once we know the hardware caught up.
or
- We really specify minimal device specs as a testing setup + test-cases (like an area with streets like we need it here), then test based on this, then merge based on this.

**Comment by bryceco** [comment]
The geekbenchScore function will estimate the performance of the hardware and that can be used to enable/disable it. For now you can enable it for any score >= 2500.

**Comment by wtimme** [comment]
> For now you can enable it for any score >= 2500.

Thanks for your input! So should I go ahead and change the code so that `shouldRasterize` is set to `YES` when the score is below 2500?

Furthermore, from a first glance, I think the list of devices could use an update. How was it compiled?

**Comment by bryceco** [comment]
> So should I go ahead and change the code so that shouldRasterize is set to YES when the score is below 2500?

Yes

 Don’t worry about updating the table because any hardware that is unrecognized is assumed to be newer and faster.

**Comment by wtimme** [comment]
Great, thanks! I've added the changes accordingly; please have another look.

If there's something missing, let me know.

**Pull request merged**
