### PR TITLE
Dark Mode support + split big Storyboard

### PR DESCRIPTION
**Pull request by patricks**
I have implemented a basic dark mode support. I also split the big main storyboard in a few smaller ones, which makes them easier to handle.

### CODE REVIEW

**Comment by LucasLarson** [comment]
@bryceco: I built and tested @patricks’s build and it’s ready for merge. Thanks to you both!

**Comment by wtimme** [comment]
Hey @patricks, thank you for the contribution! I was actually contemplating whether I should comment, but I feel like some feedback might be appreciated.

To start of, the pull request introduces two big changes:

- Support for Dark Mode
- Splitting of the storyboard into several smaller ones

Even though both might be desirable and useful, from my experience, it is usually better to focus on one change per pull request. With the current state, it is not possible for the maintainer (@bryceco) to have Dark Mode, but not a split storyboard - it‘s either both or nothing.
In addition, the more changes are introduced with a pull request, the more difficult (usually) it is to review it. (Less changes = less code to review = a more confident decision.)

Looking at the commits, there seems to be only one single commit in which the storyboard was split. Personally, I‘m a huge fan of atomic (small, dedicated) commits. The main benefit is the prevention (or at least reduction) of merge conflicts, since Git will be able to tell our intentions more easily. In addition, it makes it easier to cherry-pick particular commits, and it makes the Git log easier to read and understand.

One more observation regarding the commit messages: The ones that implement the Dark Mode just say

> Added Dark Mode Support

From the list if commit messages, I am not able to tell the view on which Dark Mode was added. Something like

> Add Dark Mode support to `BingViewController`

is a bit more descriptive. ([This article][1] was very helpful for me in this regard.)
I know this seems like a very minor detail (and, compared to failing tests, for example, it probably is), but I made the experience that writing a good commit message is worth investing some time in, be it even for just myself and the documentation.

—

So, I hope I don‘t come across as too picky. (I know I am.) My remarks are not meant to blame your code or talk badly about your efforts. Rather, I want to help and share some experience.

If you have a different opinion or other ideas, I‘m always happy about input and discussions. Again, thanks for your contribution!

[1]: https://chris.beams.io/posts/git-commit/

**Comment by patricks** [comment]
Hey @wtimme,

thanks for your feedback, I am totally at your side on every point you mentioned, it wouldn't be that hard do create two separate pull requests.

But there is one point which make me thinking about this. The PR is now open over 3 month and I have no idea, if it would make sense to drop this one and create 2 new ones. I don't know how active @bryceco works on this project. Don't get me wrong, I know that this is a private project and you sometimes haven't that much time to work on such things. But it looks like this project has potential and some other folks are really interested in the app (me included 😉).
Maybe we (specially @bryceco) should think about adding a second maintainer? 

I have a few ideas in my mind which would follow after the dark mode. One thing would be a small restructuring of the main UI, so we could make a few nice feature a little bit more visible, which are currently in my opinion a little bit too hidden.

**Comment by zlavergne** [comment]
Hey @patricks. I'm now able to review and merge PR's. Could you please do as @wtimme suggested and break this into 2 separate PR's. Then I'll be able to review them independently and get them ready for the next release.

**Comment by wtimme** [comment]
Hey guys,

Over at my fork, I've already merged a pull request with [small, dedicated commits][1]. I could see to create a new PR that targets the GoMap!! repository.

**My main motivation here is to avoid merge conflicts**, which are a real threat with a storyboard so big as `MainStoryboard.storyboard`. @patricks, I don't want you to feel that your work is not valued - it is. I just already dread the conflict resolution that will come up. 🙈

I could create a PR in about 24 hours, if you agree. (Should be more or less cherry-picking on a new branch.) Let me know what you think, guys.

[1]: https://github.com/wtimme/OSM-Completionist/pull/10/commits

**Comment by zlavergne** [comment]
That's fine with me me. If @patricks is good with it, I can review and merge @wtimme 's PR first then @patricks can rebase on top of the new commits.

**Comment by bryceco** [comment]
I’m in favor too. When I looked at it a couple days ago there were conflicts and I don’t have my laptop to verify conflict resolution.

**Comment by wtimme** [comment]
Thanks for the support, guys! I was more or less able to cherry-pick the changes, and created a dedicated pull request for it (#259). Please make sure to properly test it, especially with devices _not_ running iOS 13. I might've also missed a screen (cp. wtimme/osm-completionist#46), so a thorough look at the changes is desirable.

@patricks, I would also for you to have a look, since you know which screens to check and how to test this.

**Comment by patricks** [comment]
Hi, that’s ok for me 👍. I’ll have a look, in a few hours. It’s nice to see progress again 👏

**Pull request closed without merging**
