### PR TITLE
Setup fastlane and Travis CI

### PR DESCRIPTION
**Pull request by wtimme**
This branch adds a configuration for Travis CI and sets up fastlane. 

After merging, you can sign up for Travis CI (it's free for Open Source projects) and let it monitor your Go Map!! repository. When someone creates a new pull request, Travis CI will detect it and automatically run the unit tests. That way, you can be sure that new changes don't break the existing (tested) behaviour.

## fastlane

To test the fastlane integration yourself locally, make sure that you have [Bundler][1] installed.
Open your terminal and navigate to the `src/iOS` directory. From there, run

    % bundle install

to install fastlane. Then, execute

    % bundle exec fastlane pull_request_checks

This will run the tests from the `GoMapTests` target.

## Travis CI

Setting up Travis CI can be done from within their web interface. To get an idea of what a build looks like, have a look [here][2]. Of course, this is totally optional, but it adds a bit of a safety net to the repository, and reduces manual workload from your shoulders.

[1]: https://bundler.io/#getting-started
[2]: https://travis-ci.com/wtimme/OSM-Completionist/builds/132619702

### CODE REVIEW

**Comment by wtimme** [comment]
If desired, I'm happy to assist with creating a fastlane lane for uploading new versions (cp. wtimme/OSM-Completionist#9), so that we automate as much as possible, reducing the workload on the App Store Connect account owner (which would be @bryceco) even more.

**Comment by bryceco** [comment]
If you want to freshen this I’ll merge it, as long as using it remains totally optional. In particular I’d like to ensure that no tools other than Xcode are necessary to be installed in order to build and release the project.

**Comment by wtimme** [comment]
Thanks for the feedback!

From what I can tell, we are able to go ahead with the merge. I‘ll create another one so that we can more easily upload TestFlight builds.

**Comment by bryceco** [comment]
I haven’t looked to see what the problem is but it says there are merge conflicts.

**Comment by wtimme** [comment]
Yes, you're correct. I wasn't able to tell from GitHub's mobile version, my bad.

I've merged `master` into the branch, resolved the merge conflicts and made sure that the tests can be run from the directory `src/iOS` using

    % bundle exec fastlane pull_request_checks

Don't forget to run `bundle install` beforehand! :)

**Pull request merged**
