### PR TITLE
Updated launch screen

### PR DESCRIPTION
**Pull request by pqhf5kd**
Updated launch screen with new transparent icon and a flat background of hex 34495e, the lighter end of the AppIcon gradient.

### CODE REVIEW

**Comment by pqhf5kd** [comment]
I messed up somewhere, this pull request doesn't include the new AppIconTransparent. I did a second commit to my fork, and now GitHub thinks I've modified everything in Images.xcassets .

**Comment by pqhf5kd** [comment]
Cancel

**Comment by bryceco** [comment]
This has 106 changed files, not sure why that is.

**Comment by pqhf5kd** [comment]
@bryceco yes, somehow all images were duplicated. I've closed this, reforked and resubmitted in #409, sorry!

**Pull request closed without merging**
